config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /en|ru/, defaults: {locale: "en"} do
  # scope ":locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end
  get 'tutorial/index'
  
  root 'landing#index'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'error', to: 'landing#404', as: 'error'
  
  post 'create', to: 'landing#create', as: 'create'
  get 'download', to: 'landing#download', as: 'download'
  get 'down', to: 'landing#down', as: 'down'
  
  namespace :admin do
    root 'sessions#new'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  
    resources :sessions, only: [:new, :create, :destroy]
    resources :dashboard, only: [:index]
    resources :formats
    resources :users do
      get :active_user, on: :member
    end
  end
  
  namespace :api do
    namespace :pcs1 do
      resources :videos, only: [:index]
    end
  end
  # end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
  	Date.today.year - birthday.year
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :profile_resource
  before_action :require_owner, only: %i[edit update]

  def update
    @profile.update(profile_params)
    if @profile.save
      redirect_to user_profile_path(@profile.user)
    else
      flash[:notice] = 'Incorrect edit profile'
      render :edit
    end
  end

  private

  def profile_resource
    @profile = User.find(params[:user_id]).profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :username, :birthday)
  end

  def require_owner
    redirect_to root_path unless current_user == @profile.user
  end
end

app/views/profiles/edit.html.slim
h1 Edit profile
= form_for [current_user, @profile] do |f|
  .row
    .col-md-8.col-xs-6
      - if @profile.errors.any?
        #error_messages
          .alert.alert-danger role='alert' 
            button.close data-dismiss='alert' type='button'  x
            h2
              = fa_icon 'exclamation-triangle', text: 'Form is invalid'
            ul
              - @profile.errors.full_messages.each do |msg|
                li= msg
  .row
    .col-md-4.col-xs-6
      p= f.label :first_name
      p= f.text_field :first_name, class: 'form-control', placeholder: 'Enter your name', required: true
    .col-md-4.col-xs-6
      p= f.label :last_name
      p= f.text_field :last_name, class: 'form-control', placeholder: 'Enter your surname', required: true
  .row
    .col-md-4.col-xs-6
      p= f.label :username
      p= f.text_field :username, class: 'form-control', placeholder: 'Enter your username', required: true
    .col-md-4.col-xs-6
      p= f.label :birthday
      p= f.text_field :birthday, type: 'date', class: 'form-control'
  .row
    .col-md-4.col-xs-6
      = f.submit class: 'btn btn-success'

app/views/profiles/show.html.slim
h1 = @profile.full_name
p Birhday: #{ @profile.birthday.strftime("%B %d, %Y") }
p Age: #{ @profile.age }
p Username: #{ @profile.username }
p= link_to 'Edit profile', edit_user_profile_path(@profile.user.id), class: 'btn btn-warning'