config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /en|ru/, defaults: {locale: "en"} do
  # scope ":locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end
  get 'tutorial/index'
  
  root 'landing#index'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'error', to: 'landing#404', as: 'error'
  
  post 'create', to: 'landing#create', as: 'create'
  get 'download', to: 'landing#download', as: 'download'
  get 'down', to: 'landing#down', as: 'down'
  
  namespace :admin do
    root 'sessions#new'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  
    resources :sessions, only: [:new, :create, :destroy]
    resources :dashboard, only: [:index]
    resources :formats
    resources :users do
      get :active_user, on: :member
    end
  end
  
  namespace :api do
    namespace :pcs1 do
      resources :videos, only: [:index]
    end
  end
  # end
end

app/views/shared/_header.html.slim
.navbar.navbar-default role="navigation" 
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = fa_icon 'youtube', text: 'Youtube converter'
    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li= link_to current_user.name_space, user_profile_path(current_user)
          li= link_to t('shared.header.log_out'), logout_path
        - else
          li= link_to t('shared.header.sign_up'), signup_path
          li= link_to t('shared.header.login'), login_path
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            = t('shared.header.languages')
            span.caret
          ul.dropdown-menu
            li= link_to t('languages.en'), change_locale_path(:en)
            li= link_to t('languages.ru'), change_locale_path(:ru)