config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /en|ru/, defaults: {locale: "en"} do
  # scope ":locale", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end
  get 'tutorial/index'
  
  root 'landing#index'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get 'error', to: 'landing#404', as: 'error'
  
  post 'create', to: 'landing#create', as: 'create'
  get 'download', to: 'landing#download', as: 'download'
  get 'down', to: 'landing#down', as: 'down'
  
  namespace :admin do
    root 'sessions#new'
    get 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new', as: 'login'
    get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  
    resources :sessions, only: [:new, :create, :destroy]
    resources :dashboard, only: [:index]
    resources :formats
    resources :users do
      get :active_user, on: :member
    end
  end
  
  namespace :api do
    namespace :pcs1 do
      resources :videos, only: [:index]
    end
  end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :profile, dependent: :destroy

  validates_uniqueness_of :email
  validates_presence_of :email
  validates_presence_of :password, on: :create  

  before_create :build_profile

  def name_space
    if profile.full_name.delete(' ').length.zero?
      email
    else
      profile.full_name
    end
  end

  def user_active
    if active?
      'active'
    else
      'banned'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :user_resource, only: %i[destroy active_user]

  def index
    @users = User.order(:id)
  end

  def destroy
    @user.destroy!
    redirect_back fallback_location: root_path
  end

  def active_user
    @user.update(active: !@user.active)
    redirect_back fallback_location: root_path
  end

  private

  def user_resource
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_resourse,
                only: %i[show edit update]

  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_profile_path(@user), notice: 'Thank you for singning up!'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit; end

  private

  def current_resourse
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :active)
  end
end

app/views/admin/users/index.html.slim
h1 All users
table.table
  th ID
  th Fullname
  th Email
  th Active
  th Action
  - @users.each do |user|
    tr class="#{user.active ? 'default' : 'danger'}"
      td= user.id
      td= user.profile.full_name
      td= user.email
      td= user.user_active
      td
        .btn-group
          button.btn.btn-info.btn-sm.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' type='button'
            | Action
            span.caret
          ul.dropdown-menu
            li= link_to 'Delete user', admin_user_path(user), method: :delete
            - if user.active
              li= link_to 'The off account', active_user_admin_user_path(user)
            - else
              li= link_to 'The on account', active_user_admin_user_path(user)